<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_filter-type-label_1</name>
   <tag></tag>
   <elementGuidId>e975c674-af0a-40ac-bbf4-40e031666dcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;filter-type-label&quot;]:nth-child(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@aria-describedby = 'filter-type-label') and (position() = 3)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Trueque&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>397e805e-6103-417c-91ff-43979a13e238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c8b92eae-71ae-4335-8964-234368987277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f4ee230a-305d-40a0-894a-06f2cde58618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>filter-type-label</value>
      <webElementGuid>6247a2ce-5888-4c2f-a74d-d2f11ea1ad5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-xl border px-3 py-3 text-xs font-semibold transition border-slate-200 bg-slate-50 text-slate-600 hover:border-slate-300</value>
      <webElementGuid>12734f25-d734-4134-a9e9-34cdad1020e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trueque</value>
      <webElementGuid>06f27d88-0144-4576-b5b7-9d510632a332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9059763fe618c3badc53929819ae7796</value>
      <webElementGuid>74216960-458c-4790-98ce-2dda267a7236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@aria-describedby = 'filter-type-label') and (position() = 3)]</value>
      <webElementGuid>a2d19512-ab23-4c5b-bc27-894d5bd3ad44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@aria-describedby = 'filter-type-label') and (position() = 3)]</value>
      <webElementGuid>ac39ab54-03a8-4bd0-be8d-e746616f36bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Trueque' or . = 'Trueque')]</value>
      <webElementGuid>1b41d6db-50c4-48ff-a8da-2bc881e479df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
