<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_filter-type-label_2</name>
   <tag></tag>
   <elementGuidId>10473bf8-ff68-4efd-9adb-88163c9b4bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;filter-type-label&quot;]:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@aria-describedby = 'filter-type-label') and (position() = 1)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Ambos&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fb2b4a5-51ad-4759-a04f-ad07274d3ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0ebf6e9-fc44-484b-875e-e4591b0600ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b5202bc5-cdfe-4be9-8245-ee3bd3b6e248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>filter-type-label</value>
      <webElementGuid>21fde4ef-1d5a-4ca2-bb1d-5f3900bb9ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-xl border px-3 py-3 text-xs font-semibold transition border-slate-200 bg-slate-50 text-slate-600 hover:border-slate-300</value>
      <webElementGuid>a260fd15-936a-46bb-9b0c-6b9fff7a47b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ambos</value>
      <webElementGuid>6040871b-6c27-46ba-a78e-79000a3b76c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f5c47fd4bf25200a3370f76e1564c895</value>
      <webElementGuid>08bceaf8-5b61-4fac-9d39-e89c78cef3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@aria-describedby = 'filter-type-label') and (position() = 1)]</value>
      <webElementGuid>881ffe6d-0ce3-4f20-837b-97d3720f4584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@aria-describedby = 'filter-type-label') and (position() = 1)]</value>
      <webElementGuid>9a6b1571-3b74-40bb-a306-8ae7d52f84bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Ambos' or . = 'Ambos')]</value>
      <webElementGuid>d9736545-62b4-4628-acd6-631d202fe449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
