<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_</name>
   <tag></tag>
   <elementGuidId>fbaa533d-974a-45b2-9797-fb2699727f0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_r_q_</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '_r_q_' and @placeholder = '••••••••' and @type = 'password' and @name = 'password']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = '_r_q_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;••••••••&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff203ddd-c4e3-4c83-91d0-b862f23c95de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_r_q_</value>
      <webElementGuid>f0d59183-ed8d-409a-96e5-dbf1699f0415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>••••••••</value>
      <webElementGuid>6f2b7ffc-5665-48a0-87d5-23241f5fdcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-3.5 rounded-t-lg border-0 border-b-2 text-sm font-medium text-slate-900 placeholder-slate-300 outline-none transition-all duration-200 bg-slate-100/60 border-slate-200 focus:bg-white focus:border-slate-900 pr-11</value>
      <webElementGuid>0f93e749-060e-4f1e-8f1c-9037a220d864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>05f19176-643a-4db9-b2b7-635622a27460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a1ff7109-abec-49ad-af31-d66d92d93502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-754e9588e44f7d30b5bd83a091b00bbf</value>
      <webElementGuid>9451c55a-aa53-4803-a67e-eb32aabfc0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = '_r_q_']</value>
      <webElementGuid>6bafb5b5-34b9-4ba0-b0b8-61b3c34c1258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = '_r_q_']</value>
      <webElementGuid>37f72ceb-4181-4911-b596-f2a59bbf9b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_r_q_' and @placeholder = '••••••••' and @type = 'password' and @name = 'password']</value>
      <webElementGuid>2f85deb6-76fd-486d-89b9-3420b59cc3ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
