analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3500388,"name"\:"Cellphone Shop Trial \#3500388","teamId"\:3496506,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3509433,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3496506,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
